

<Atm>:
    StartPage:
        name: 'start'
        Button:
            text: 'goto selextion'
            on_release: app.root.current='selection'

    SelectionPage:
        name: 'selection'
        Button:
            text: 'goto selextion'
            on_release: app.root.current='payment'


    PaymentPage:
        name: 'payment'
        Button:
            text: 'goto selextion'
            on_release: app.root.current='start'
